---
title: "HW1"
author: "Connie Zhang"
date: "2024-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q0: Survey

Question 0A: Please let us know your preferred name.

> Connie. 

Question 0B: Please read the syllabus in its entirety and write, “I have read and understood the entire syllabus,” for this question. If you have any questions about the syllabus (for example, on the homework submission policy or collaboration policy), you may ask them here.

> I have read and understood the entire syllabus. 

Question 0C: If any, please briefly describe the courses you have taken at UW that involve coding (in any language) so far and how familiar/comfortable you are in coding in R. (Note: We do not expect you to have taken any such courses already.)

> BIOST 514 and 515 involves codingn in R. I am comfortable with coding in R. I have created shiny apps and done simulation studies in R. 

Question 0D: What do you hope to learn from this course? (It is alright if you leave this blank, but it would be helpful to hear your thoughts.)

> I hope to learn more about how to write R packages, code testing and debugging. 

## Q1: Setting up an R package and GitHub

## Q2: Simulating the Central Limit Theorem
